from twilio.rest import Client


TWILIO_ACCOUNT_SID = None


TWILIO_ACCOUNT_AUTH_TOKEN = None


TWILIO_CLIENT = Client(TWILIO_ACCOUNT_SID, TWILIO_ACCOUNT_AUTH_TOKEN)


TWILIO_ACCOUNT_SENDER_PHONE_NUMBER = '+xx00000000'


SMS_TARGET_PHONE_NUMBER = '+xx00000000'


ARGS_FOR_SEND_SMS = {'to': SMS_TARGET_PHONE_NUMBER, 'from_': TWILIO_ACCOUNT_SENDER_PHONE_NUMBER, 'body': 'Bless you World!'}


MESSAGE = TWILIO_CLIENT.messages.create(**ARGS_FOR_SEND_SMS)


MESSAGE_SID = MESSAGE.sid


print(f'Created Twilio Message. SID is: {MESSAGE_SID}') 
